server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        enabled: true  # 开启服务注册发现
#      server-addr: http://47.113.224.195:8848 # nacos地址
        server-addr: 192.168.148.100:8848
    gateway:
      routes:
        # 告警服务
        - id: alert-service # 路由标示，必须唯一
          uri: lb://alert-service
          predicates:
            - Path=/alertRules/**,/notifications/**,/responsibilities/**
        # websocket服务
        - id: websocket-service
          uri: lb:ws://alert-service
          predicates:
            - Path=/ws/**,/ws
        # 后端服务
        - id: backend-service
          uri: lb://backend-service
          predicates:
            - Path=/backend/**,/frontend/**,/mobile/**,/graph/**,/markdownContents/**,/errors/**,/milvus/**
#        # 前端服务
#        - id: frontend-service
#          uri: lb://frontend-service
#          predicates:
#            - Path=/frontend/**
        # 图表服务
#        - id: graph-service
#          uri: lb://graph-service
#          predicates:
#            - Path=/graph/**,/markdownContents/**,/errors/**
        # 消息服务
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/messages/**,
#        # ai服务
#        - id: milvus-service
#          uri: lb://milvus-service
#          predicates:
#            - Path=/milvus/**
#        # 移动服务
#        - id: mobile-service
#          uri: lb://mobile-service
#          predicates:
#            - Path=/mobile/**
#        # 项目服务
#        - id: project-service
#          uri: lb://project-service
#          predicates:
#            - Path=/projects/**,/roles/**
#        # 角色服务
#        - id: role-service
#          uri: lb://role-service
#          predicates:
#            - Path=/role/**
        # 用户服务
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/projects/**,/roles/**
      default-filters:
        - AddRequestHeader=Truth,this is request header~
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: # 允许哪些网站的跨域请求
#              - "*"
#            allowedMethods: # 允许的跨域ajax的请求方式
#              - "GET"
#              - "POST"
#              - "DELETE"
#              - "PUT"
#              - "OPTIONS"
#            allowedHeaders: "*" # 允许在请求中携带的头信息
#            allowCredentials: true # 是否允许携带cookie
#            maxAge: 360000 # 这次跨域检测的有效期
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"  # 使用allowedOriginPatterns代替allowedOrigins
            allowedMethods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600